# conf/agent/default.yaml
# The name of tools and sub-agents defined in: apps/miroflow-agent/src/config/settings.py
# Each sub-agent prompt is written in: apps/miroflow-agent/src/utils/prompt_utils.py
main_agent:
  tools:
    - tool-python
    - tool-vqa-enhanced  # Enhanced vision understanding with multi-turn verification
    - tool-vqa          # Fallback to commercial Claude vision
    - tool-audio-enhanced  # Enhanced audio understanding with multi-turn verification
    - tool-transcribe
    - tool-video-enhanced  # Enhanced video understanding with temporal analysis
    - tool-reasoning
    - tool-reader
  max_turns: 20  # Maximum number of turns for main agent execution

sub_agents:
  agent-browsing:
    tools:
      - tool-google-search
      - tool-vqa-enhanced  # Enhanced vision understanding with multi-turn verification
      - tool-vqa          # Fallback to commercial Claude vision
      - tool-audio-enhanced  # Enhanced audio understanding with multi-turn verification
      - tool-video-enhanced  # Enhanced video understanding with temporal analysis
      - tool-reader
      - tool-python
    max_turns: 20

keep_tool_result: -1 